### ISSUE TITLE
Version 5.1.2 for iOS & Android

### ISSUE THREAD

**Issue by fix89** [lilili87222/chartboost-ane#4]
Can you now update the ane for Version 5.1.2? I mean for iOS too. Thanks!

**Comment by lilili87222** [comment]
ok

**Comment by fix89** [comment]
Great! Do you have an ETA?

**Comment by fix89** [comment]
Hi there! Do you have some news? Thanks

**Comment by lilili87222** [comment]
chartboost sdk for ios has bug

**Comment by lilili87222** [comment]
updated,add video ad,fix ios 8 rotation bug.
