### ISSUE TITLE
Video ad

### ISSUE THREAD

**Issue by ErikSom** [lilili87222/chartboost-ane#5]
Hi,

I'm using your library and successfully showing interstitials.
However i'm not able to show video's in test mode, nothing happens?

Using the following code:

if(chartboost.isVideoAppReady()){
	chartboost.showRewardedVideo();
}else{
	chartboost.cacheRewardedVideo();
}

private function onAdReceived(event:ChartboostEvent):void{
	chartboost.showInterstitial();
}

Thanks for your reply!!

Best

**Comment by lilili87222** [comment]
private function onAdReceived(event:ChartboostEvent):void{
trace(event.type,event.data);//log out to find the reason
}

**Comment by lilili87222** [comment]
updated,add video ad,fix ios 8 rotation bug.
