### ISSUE TITLE
Upgrading to new Chartboost SDK 5.1.3 to fix bug?

### ISSUE THREAD

**Issue by hybridmindset** [lilili87222/chartboost-ane#6]
Is the iOS bug fixed in the new chartboost sdk 5.1.3? I need this ane to work on both Android and iOS.

https://answers.chartboost.com/hc/en-us/articles/201219435-iOS-SDK-Download

**Comment by lilili87222** [comment]
updated,add video ad,fix ios 8 rotation bug.
